CREATE SEQUENCE S_APP_STATISTIC INCREMENT BY 1 START WITH 957877 MINVALUE 957877;
CREATE SEQUENCE S_APP_USER INCREMENT BY 1 START WITH 8 MINVALUE 8;
CREATE SEQUENCE S_SCENARIO INCREMENT BY 1 START WITH 9 MINVALUE 9;
CREATE SEQUENCE S_TASK INCREMENT BY 1 START WITH 192 MINVALUE 192;
CREATE SEQUENCE S_TASKGROUP INCREMENT BY 1 START WITH 18 MINVALUE 18;
CREATE SEQUENCE S_TASKGROUP_RANK INCREMENT BY 1 START WITH 65 MINVALUE 65;
CREATE SEQUENCE S_TASK_RANK INCREMENT BY 1 START WITH 205 MINVALUE 205;