ALTER TABLE APP_STATISTIC ADD  CONSTRAINT TASK_APP_STATISTIC FOREIGN KEY (TASK_ID) REFERENCES TASK (ID) ON DELETE CASCADE;
ALTER TABLE SCENARIO ADD  CONSTRAINT APP_USER_SCENARIO FOREIGN KEY (APP_USER_ID) REFERENCES APP_USER (ID) ON DELETE CASCADE;
ALTER TABLE SCENARIO_TABLE ADD  CONSTRAINT SCENARIO_SCENARIO_TABLE FOREIGN KEY (SCENARIO_ID) REFERENCES SCENARIO (ID) ON DELETE CASCADE;
ALTER TABLE TASK ADD  CONSTRAINT TASKGROUP_TASK FOREIGN KEY (TASKGROUP_ID) REFERENCES TASKGROUP (ID) ON DELETE CASCADE;
ALTER TABLE TASKGROUP ADD  CONSTRAINT SCENARIO_TASKGROUP FOREIGN KEY (SCENARIO_ID) REFERENCES SCENARIO (ID) ON DELETE CASCADE;