-- ---------------------------------------- --
-- ---- DDL for Tables of SQLCOACH ---- --
-- ---------------------------------------- --

DROP TABLE APP_STATISTIC CASCADE
//
CREATE TABLE APP_STATISTIC (
  ID	 DEC(10,0) NOT NULL,
  TASK_ID	 DEC(10,0) NOT NULL,
  SUCCESS	 CHAR(1) NOT NULL CHECK SUCCESS IN ('0','1') ,
  QUERY	 VARCHAR(2048) NOT NULL,
  SESSION_ID	 VARCHAR(255) NOT NULL,
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
 PRIMARY KEY (ID)
)
//
CREATE INDEX app_statistic ON APP_STATISTIC (DATECREATE ASC, SUCCESS ASC)
//

DROP TABLE APP_STATISTIC_MONTH CASCADE
//
CREATE TABLE APP_STATISTIC_MONTH (
  JAHR	 CHAR(4),
  MONAT	 CHAR(2),
  ANZAHL	 DEC(10,0),
  INSERTED	 TIMESTAMP DEFAULT TIMESTAMP
)
//

DROP TABLE APP_STATISTIC_YEAR CASCADE
//
CREATE TABLE APP_STATISTIC_YEAR (
  JAHR	 CHAR(4),
  ANZAHL	 DEC(10,0),
  INSERTED	 TIMESTAMP DEFAULT TIMESTAMP
)
//

DROP TABLE APP_USER CASCADE
//
CREATE TABLE APP_USER (
  ID	 DEC(10,0) NOT NULL,
  NICKNAME	 VARCHAR(24) NOT NULL,
  PASSWORD	 VARCHAR(64) NOT NULL,
  TITLE	 VARCHAR(24),
  FIRSTNAME	 VARCHAR(64),
  LASTNAME	 VARCHAR(64),
  EMAIL	 VARCHAR(64),
  ROLE	 VARCHAR(64),
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
 PRIMARY KEY (ID)
)
//
ALTER TABLE APP_USER ADD CONSTRAINT app_user_nick UNIQUE (NICKNAME)
//

DROP TABLE SCENARIO CASCADE
//
CREATE TABLE SCENARIO (
  ID	 DEC(10,0) NOT NULL,
  APP_USER_ID	 DEC(10,0) NOT NULL,
  DESCRIPTION	 VARCHAR(255) NOT NULL,
  DATASOURCE	 VARCHAR(64) NOT NULL,
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATABASEPRODUCTNAME varchar(64),
  SAMPLESOLUTIONHINTCOUNT integer,
 PRIMARY KEY (ID)
)
//

ALTER TABLE SCENARIO ADD CONSTRAINT scenario_description UNIQUE (DESCRIPTION)
//

DROP TABLE SCENARIO_TABLE CASCADE
//
CREATE TABLE SCENARIO_TABLE (
  SCENARIO_ID	 DEC(10,0) NOT NULL,
  SCENARIO_TABLE	 VARCHAR(255) NOT NULL,
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
 PRIMARY KEY (SCENARIO_ID, SCENARIO_TABLE)
)
//

DROP TABLE TASK CASCADE
//
CREATE TABLE TASK (
  ID	 DEC(10,0) NOT NULL,
  TASKGROUP_ID	 DEC(10,0) NOT NULL,
  RANK	 DEC(10,0) NOT NULL,
  DESCRIPTION	 VARCHAR(2048) NOT NULL,
  QUERY	 VARCHAR(2048) NOT NULL,
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  HINT	 VARCHAR(2048),
  HINT_TRIALS	 INTEGER NOT NULL DEFAULT           2,
  SOLUTION_TRIALS	 INTEGER NOT NULL DEFAULT           3,
 PRIMARY KEY (ID)
)
//

DROP TABLE TASKGROUP CASCADE
//
CREATE TABLE TASKGROUP (
  ID	 DEC(10,0) NOT NULL,
  SCENARIO_ID	 DEC(10,0) NOT NULL,
  RANK	 DEC(10,0) NOT NULL,
  DESCRIPTION	 VARCHAR(255) NOT NULL,
  DATECREATE	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  DATELASTMOD	 TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
 PRIMARY KEY (ID)
)
//

